
#SERVER
SERVER_PORT: 8080
ACTIVE_PROFILE: prod

#Docker
CONTAINER_PORT: 8000

#Database
POSTGRES_USER: sidof
POSTGRES_PASSWORD: sidof1/@
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_DATABASE: apphiro

#EMAIL CONFIG
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: sidofdountio406@gmail.com
EMAIL_PASSWORD: esltgpxbdqoonuoc
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}